insert into karyawan(nik, nama) values("00222","ENDANG TABRI ATIK");
insert into karyawan(nik, nama) values("00223","KARSIYAH");
insert into karyawan(nik, nama) values("00224","SUTOMO");
insert into karyawan(nik, nama) values("00225","ALFIYAH");
insert into karyawan(nik, nama) values("00226","WIWIK SRIANI");
insert into karyawan(nik, nama) values("00228","TAMUN");
insert into karyawan(nik, nama) values("00232","LASMIYATI");
insert into karyawan(nik, nama) values("00233","SISWATI");
insert into karyawan(nik, nama) values("00234","SUYATIN");
insert into karyawan(nik, nama) values("00235","TRI DHAMAYANTI");
insert into karyawan(nik, nama) values("00238","JAMIL A");
insert into karyawan(nik, nama) values("00242","YUSWATI FIATININGSIH");
insert into karyawan(nik, nama) values("00254","HINDUN AMAMI");
insert into karyawan(nik, nama) values("00268","SUNANIK");
insert into karyawan(nik, nama) values("00354","SUKARTO");
insert into karyawan(nik, nama) values("00428","SIS SRI ASMINI");
insert into karyawan(nik, nama) values("00444","MUHADI");
insert into karyawan(nik, nama) values("00445","ABDUL MANAB");
insert into karyawan(nik, nama) values("00447","SITI ROMLAH A");
insert into karyawan(nik, nama) values("00448","HENIK KUSUMAWATI");
insert into karyawan(nik, nama) values("00452","SUPARMAN");
insert into karyawan(nik, nama) values("00454","KALIM");
insert into karyawan(nik, nama) values("00458","PATUN");
insert into karyawan(nik, nama) values("00459","RUPIAH");
insert into karyawan(nik, nama) values("00460","MUKTI");
insert into karyawan(nik, nama) values("00461","MISDAH");
insert into karyawan(nik, nama) values("00463","KASIATI");
insert into karyawan(nik, nama) values("00464","SUGIARTI");
insert into karyawan(nik, nama) values("00465","SARIMAH");
insert into karyawan(nik, nama) values("00466","WAHMOTIK");
insert into karyawan(nik, nama) values("00467","KASIYATIN");
insert into karyawan(nik, nama) values("00468","ULFAH KHASANAH");
insert into karyawan(nik, nama) values("00469","MOH. SAMAK BASORI");
insert into karyawan(nik, nama) values("00470","JUARI");
insert into karyawan(nik, nama) values("00472","SYAROTIN");
insert into karyawan(nik, nama) values("00473","SUJIMAN");
insert into karyawan(nik, nama) values("00474","SUDARSONO");
insert into karyawan(nik, nama) values("00476","PATRI");
insert into karyawan(nik, nama) values("00477","SUKESIH");
insert into karyawan(nik, nama) values("00478","SULIHATI");
insert into karyawan(nik, nama) values("00479","PONIMAH A.");
insert into karyawan(nik, nama) values("00482","YUNIARTI");
insert into karyawan(nik, nama) values("00490","FX. AGUS PRASETYO  SE");
insert into karyawan(nik, nama) values("00516","HENY HANDAYANI");
insert into karyawan(nik, nama) values("00535","ZURAINI");
insert into karyawan(nik, nama) values("00570","TATIK SISWATI");
insert into karyawan(nik, nama) values("00574","TUMIATI");
insert into karyawan(nik, nama) values("00575","SITI JUWARIYAH");
insert into karyawan(nik, nama) values("00576","MISTIN");
insert into karyawan(nik, nama) values("00578","DHOLIFAH");
insert into karyawan(nik, nama) values("00579","ASTUTIK");
insert into karyawan(nik, nama) values("00581","ALI IMRON");
insert into karyawan(nik, nama) values("00582","SUIN NINGSIH");
insert into karyawan(nik, nama) values("00584","DURASAN");
insert into karyawan(nik, nama) values("00587","NATUN");
insert into karyawan(nik, nama) values("00588","MARFUATIN");
insert into karyawan(nik, nama) values("00589","MUNTAMAH");
insert into karyawan(nik, nama) values("00639","SUNAWI");
insert into karyawan(nik, nama) values("00643","SRI SULASTRI");
insert into karyawan(nik, nama) values("00645","SUNIN NARTI");
insert into karyawan(nik, nama) values("00668","SUKRI");
insert into karyawan(nik, nama) values("00679","NURHAMID");
insert into karyawan(nik, nama) values("00680","SADIONO");
insert into karyawan(nik, nama) values("00690","DWI SISWOYO");
insert into karyawan(nik, nama) values("00704","SISWANTO");
insert into karyawan(nik, nama) values("00720","BUYUNG");
insert into karyawan(nik, nama) values("00761","KASIATI");
insert into karyawan(nik, nama) values("00762","SULASTRI");
insert into karyawan(nik, nama) values("00763","AMINAH");
insert into karyawan(nik, nama) values("00764","MOHAMAD YASIN");
insert into karyawan(nik, nama) values("00765","SOLIKIN");
insert into karyawan(nik, nama) values("00798","WIYOTO DARSONO");
insert into karyawan(nik, nama) values("00799","MISTIANAWATI");
insert into karyawan(nik, nama) values("00835","HARIYATI");
insert into karyawan(nik, nama) values("00853","AIDA");
insert into karyawan(nik, nama) values("00854","SOFII");
insert into karyawan(nik, nama) values("00856","SUMIANAH");
insert into karyawan(nik, nama) values("00857","TUNIK A");
insert into karyawan(nik, nama) values("00862","TOHIR");
insert into karyawan(nik, nama) values("00866","HARIYONO");
insert into karyawan(nik, nama) values("00870","IKSAN");
insert into karyawan(nik, nama) values("00881","SITI CHAROJAH");
insert into karyawan(nik, nama) values("00882","ABD. KODIR JAELANI");
insert into karyawan(nik, nama) values("00906","NIKAYAH");
insert into karyawan(nik, nama) values("00909","FAKIH");
insert into karyawan(nik, nama) values("00910","SUPARMAN A");
insert into karyawan(nik, nama) values("00912","ABDUL ROCHIM");
insert into karyawan(nik, nama) values("00953","JAMIAN");
insert into karyawan(nik, nama) values("00962","RAKHMAN SETYO HADI");
insert into karyawan(nik, nama) values("00968","WARSONO");
insert into karyawan(nik, nama) values("00969","IDA RACHMAWATI");
insert into karyawan(nik, nama) values("00974","GATOT HARIADI");
insert into karyawan(nik, nama) values("00975","SUNARTO");
insert into karyawan(nik, nama) values("01031","SUNARKO");
insert into karyawan(nik, nama) values("01055","BAMBANG W.");
insert into karyawan(nik, nama) values("01057","SUKRIYANTO");
insert into karyawan(nik, nama) values("01058","MOCH. SUKRIM");
insert into karyawan(nik, nama) values("01062","SADI");
insert into karyawan(nik, nama) values("01148","TOMO");
insert into karyawan(nik, nama) values("01161","ABDUL ROKHIM");
insert into karyawan(nik, nama) values("01166","HASAN YUSRON");
insert into karyawan(nik, nama) values("01175","ABDUL MUNIB");
insert into karyawan(nik, nama) values("01179","HERCULES WILLY MARYANTO");
insert into karyawan(nik, nama) values("01194","TARUP PRIYANTO");
insert into karyawan(nik, nama) values("01227","ERY SANDY");
insert into karyawan(nik, nama) values("01273","SUBAKIR A ROKHIM");
insert into karyawan(nik, nama) values("01294","JAMARI");
insert into karyawan(nik, nama) values("01315","PARDI PARYONO");
insert into karyawan(nik, nama) values("01345","SUPRAYITNO A");
insert into karyawan(nik, nama) values("01389","CHOIRUL ANAM");
insert into karyawan(nik, nama) values("01432","YULIANA LIMSIANI  Dra");
insert into karyawan(nik, nama) values("01443","WARTONO B");
insert into karyawan(nik, nama) values("01501","SITI ROMLAH");
insert into karyawan(nik, nama) values("01503","BUDIONO");
insert into karyawan(nik, nama) values("01504","YULI AMALIA");
insert into karyawan(nik, nama) values("01506","DIDIK DJUNAEDI");
insert into karyawan(nik, nama) values("01507","EDI MOHAROM");
insert into karyawan(nik, nama) values("01508","SOKEH");
insert into karyawan(nik, nama) values("01550","SITI ROHMAWATI");
insert into karyawan(nik, nama) values("01551","ANIK WINARTI");
insert into karyawan(nik, nama) values("01579","SUMAMIK");
insert into karyawan(nik, nama) values("01580","FATIMAH B.");
insert into karyawan(nik, nama) values("01582","SOLIHIN");
insert into karyawan(nik, nama) values("01585","NURBAIYAH");
insert into karyawan(nik, nama) values("01586","TINAYAH WIDIYAWATI");
insert into karyawan(nik, nama) values("01604","MAHMUDAH");
insert into karyawan(nik, nama) values("01619","RUDI HARTONO B");
insert into karyawan(nik, nama) values("01636","LINDA SUSILOWATI  SE");
insert into karyawan(nik, nama) values("01668","DUL. KALIM");
insert into karyawan(nik, nama) values("01694","SYAIFUL RAHMAN");
insert into karyawan(nik, nama) values("01696","SYAFAK");
insert into karyawan(nik, nama) values("01697","PONIMAN");
insert into karyawan(nik, nama) values("01698","PONIMAN");
insert into karyawan(nik, nama) values("01707","LUKAS ADI LEGOWO SUNARDI");
insert into karyawan(nik, nama) values("01708","JOKO WASKITO");
insert into karyawan(nik, nama) values("01729","TAKIM");
insert into karyawan(nik, nama) values("01730","SYAIFUL ANWAR");
insert into karyawan(nik, nama) values("01731","RIDWAN");
insert into karyawan(nik, nama) values("01732","YASIN");
insert into karyawan(nik, nama) values("01734","TIKNO HADI");
insert into karyawan(nik, nama) values("01735","KASTO");
insert into karyawan(nik, nama) values("01736","WARDI");
insert into karyawan(nik, nama) values("01737","MUHAMMAD SOLEH  ST");
insert into karyawan(nik, nama) values("01738","AHMAT SAIFUDIN");
insert into karyawan(nik, nama) values("01742","TATIK B.");
insert into karyawan(nik, nama) values("01744","WARNIK KUSUMAWATI");
insert into karyawan(nik, nama) values("01745","KHULIKAH LINDA SARI");
insert into karyawan(nik, nama) values("01746","TARIP");
insert into karyawan(nik, nama) values("01747","WAKIDI");
insert into karyawan(nik, nama) values("01748","DAYAT");
insert into karyawan(nik, nama) values("01749","ELISABETH HARTUTIK");
insert into karyawan(nik, nama) values("01750","PUJI ASTUTIK");
insert into karyawan(nik, nama) values("01752","KARIYAJI");
insert into karyawan(nik, nama) values("01753","SUMIATIN");
insert into karyawan(nik, nama) values("01754","SRI KUSTINAH");
insert into karyawan(nik, nama) values("01755","DEDIK REFFIANTO");
insert into karyawan(nik, nama) values("01757","JAMIYAH");
insert into karyawan(nik, nama) values("01758","SAMSUL ARIF");
insert into karyawan(nik, nama) values("01759","SLAMET HARIYANTO");
insert into karyawan(nik, nama) values("01760","ROSID");
insert into karyawan(nik, nama) values("01762","SUHARTO");
insert into karyawan(nik, nama) values("01769","BUDI WIYAJI");
insert into karyawan(nik, nama) values("01774","RIADI");
insert into karyawan(nik, nama) values("01784","WARTONO");
insert into karyawan(nik, nama) values("01786","SANTOSO");
insert into karyawan(nik, nama) values("01794","ABDULJALIL");
insert into karyawan(nik, nama) values("01795","ARIFIN");
insert into karyawan(nik, nama) values("01796","SLAMET MULYONO");
insert into karyawan(nik, nama) values("01797","SAYUDI");
insert into karyawan(nik, nama) values("01799","HARIADI");
insert into karyawan(nik, nama) values("01800","SLAMET MULYONO B");
insert into karyawan(nik, nama) values("01801","SUPADI  Drs");
insert into karyawan(nik, nama) values("01803","ABDUL LATIEF");
insert into karyawan(nik, nama) values("01804","SUJONO");
insert into karyawan(nik, nama) values("01805","DASIYAH");
insert into karyawan(nik, nama) values("01806","SUDARMAN");
insert into karyawan(nik, nama) values("01807","SUMIASIH A");
insert into karyawan(nik, nama) values("01808","DIKSONO");
insert into karyawan(nik, nama) values("01809","SYAMSUDDUKHA");
insert into karyawan(nik, nama) values("01825","ANDY JULIANTO");
insert into karyawan(nik, nama) values("01851","AHMAD SYAFII");
insert into karyawan(nik, nama) values("01863","DWI SUPRIYANTO");
insert into karyawan(nik, nama) values("01872","SUGENG DWI ATMOJO");
insert into karyawan(nik, nama) values("01873","DOYO MULYO");
insert into karyawan(nik, nama) values("01886","KHAMIM");
insert into karyawan(nik, nama) values("01887","WIYONO");
insert into karyawan(nik, nama) values("01894","MOCH. SAIHU");
insert into karyawan(nik, nama) values("01895","SYAFII");
insert into karyawan(nik, nama) values("01896","MUHAMMAD YUSUF");
insert into karyawan(nik, nama) values("01897","WAHYUDI A.");
insert into karyawan(nik, nama) values("01898","KARNAPI");
insert into karyawan(nik, nama) values("01899","SOKHEH");
insert into karyawan(nik, nama) values("01902","SUTRISNO");
insert into karyawan(nik, nama) values("01903","SUTRISNO D.");
insert into karyawan(nik, nama) values("01904","PUJIONO B.");
insert into karyawan(nik, nama) values("01905","DODIK YUNANTO ADI");
insert into karyawan(nik, nama) values("01933","KUSNO AFANANI");
insert into karyawan(nik, nama) values("01934","PUJIONO");
insert into karyawan(nik, nama) values("01935","IDA SOLIKHA");
insert into karyawan(nik, nama) values("01936","KASDANI");
insert into karyawan(nik, nama) values("01937","ABDUL KHOLIQ A.");
insert into karyawan(nik, nama) values("01938","MOKHAMMAD ROFII");
insert into karyawan(nik, nama) values("01940","PURNOMO");
insert into karyawan(nik, nama) values("01944","ABDUL ROCHMAN");
insert into karyawan(nik, nama) values("01945","DJAMAL");
insert into karyawan(nik, nama) values("01946","JAHYONO");
insert into karyawan(nik, nama) values("01947","DARSONO");
insert into karyawan(nik, nama) values("01948","MOH. ALIANFAH");
insert into karyawan(nik, nama) values("01949","BUADI");
insert into karyawan(nik, nama) values("01950","SYUKUR");
insert into karyawan(nik, nama) values("01951","NAPI");
insert into karyawan(nik, nama) values("01957","NURIYATI");
insert into karyawan(nik, nama) values("01958","YUSUF AFANDI");
insert into karyawan(nik, nama) values("01959","DASIYAH B.");
insert into karyawan(nik, nama) values("01960","RIFAI");
insert into karyawan(nik, nama) values("01963","ABDUL SHOMAD");
insert into karyawan(nik, nama) values("01969","SUMARNO");
insert into karyawan(nik, nama) values("01970","SAMSUL HADI MULYONO");
insert into karyawan(nik, nama) values("01971","SULIKHAN");
insert into karyawan(nik, nama) values("01972","ROKHMAN");
insert into karyawan(nik, nama) values("02025","MUDJITO");
insert into karyawan(nik, nama) values("02057","NASIKHIN");
insert into karyawan(nik, nama) values("02091","HARIANTO");
insert into karyawan(nik, nama) values("02096","MULYONO");
insert into karyawan(nik, nama) values("02098","AKHMAD ZAINUL");
insert into karyawan(nik, nama) values("02102","PUJI PRAYITNO");
insert into karyawan(nik, nama) values("02105","MUCHAMAD YUNUS");
insert into karyawan(nik, nama) values("02106","SUGENG SUMARDI");
insert into karyawan(nik, nama) values("02116","MUSTAKIM");
insert into karyawan(nik, nama) values("02128","MISDRAN");
insert into karyawan(nik, nama) values("02130","KHAMID");
insert into karyawan(nik, nama) values("02139","ABDUL ROHMAN IMANSYAH");
insert into karyawan(nik, nama) values("02158","TAUKHID");
insert into karyawan(nik, nama) values("02159","SALAM");
insert into karyawan(nik, nama) values("02161","JUDI HERNANG WIDODO");
insert into karyawan(nik, nama) values("02184","SULARNO");
insert into karyawan(nik, nama) values("02185","ADLU SYUHADA");
insert into karyawan(nik, nama) values("02186","ACHMAD AMIN");
insert into karyawan(nik, nama) values("02187","IMRON A.");
insert into karyawan(nik, nama) values("02188","WARIANTO");
insert into karyawan(nik, nama) values("02189","SISWANDI");
insert into karyawan(nik, nama) values("02190","NUR ALI B");
insert into karyawan(nik, nama) values("02194","KHOIRUL ANAM");
insert into karyawan(nik, nama) values("02196","NURIYANTO");
insert into karyawan(nik, nama) values("02197","NANANG WIJAYANTO");
insert into karyawan(nik, nama) values("02199","BUASAN");
insert into karyawan(nik, nama) values("02216","ARIEF ARIYANTO");
insert into karyawan(nik, nama) values("02217","WAHYUDI");
insert into karyawan(nik, nama) values("02224","ISMAIL A");
insert into karyawan(nik, nama) values("02255","IKROM");
insert into karyawan(nik, nama) values("02262","BAMBANG HERMANTO");
insert into karyawan(nik, nama) values("02268","TOHARI");
insert into karyawan(nik, nama) values("02269","NARTO");
insert into karyawan(nik, nama) values("02270","SAMSUL MUARIF");
insert into karyawan(nik, nama) values("02271","ACH. TAUFIQ");
insert into karyawan(nik, nama) values("02277","SUHERMAN");
insert into karyawan(nik, nama) values("02278","SYAHRUL IMRON");
insert into karyawan(nik, nama) values("02288","SOELAH");
insert into karyawan(nik, nama) values("02289","MANAKIB");
insert into karyawan(nik, nama) values("02296","TRI WAHYUDI");
insert into karyawan(nik, nama) values("02317","HONI ROFIKO");
insert into karyawan(nik, nama) values("02337","MARKABAN");
insert into karyawan(nik, nama) values("02350","ZULKARNAIN M.");
insert into karyawan(nik, nama) values("02440","MULYONO REJO");
insert into karyawan(nik, nama) values("02441","SOLIKIN B.");
insert into karyawan(nik, nama) values("02442","KUSNO KRIESTIANTO");
insert into karyawan(nik, nama) values("02443","JUMADI");
insert into karyawan(nik, nama) values("02444","SAMUJI");
insert into karyawan(nik, nama) values("02446","SANAJI");
insert into karyawan(nik, nama) values("02447","ABD. ROHMAN A.");
insert into karyawan(nik, nama) values("02448","ABDUL MANAF");
insert into karyawan(nik, nama) values("02456","ABDUL KODIR");
insert into karyawan(nik, nama) values("02457","AGUS BUDI SANTOSO");
insert into karyawan(nik, nama) values("02484","SHODIK");
insert into karyawan(nik, nama) values("02486","JAKFAR");
insert into karyawan(nik, nama) values("02487","SUMINI");
insert into karyawan(nik, nama) values("02497","EKO SUPRAPTO");
insert into karyawan(nik, nama) values("02528","MUSLIMIN A");
insert into karyawan(nik, nama) values("02529","SUTRISNO");
insert into karyawan(nik, nama) values("02585","M. SHOLEH A.");
insert into karyawan(nik, nama) values("02586","FANUS AFANDI");
insert into karyawan(nik, nama) values("02587","E. WITYANTO HERU SUBRATA");
insert into karyawan(nik, nama) values("02588","KARNOTO");
insert into karyawan(nik, nama) values("02589","VITA KUSUMA KATINI");
insert into karyawan(nik, nama) values("02590","YASIN B.");
insert into karyawan(nik, nama) values("02592","SANURI");
insert into karyawan(nik, nama) values("02593","HADI PRAYITNO");
insert into karyawan(nik, nama) values("02595","NUR BIDIN");
insert into karyawan(nik, nama) values("02596","MUDAIYAH");
insert into karyawan(nik, nama) values("02597","MAMAN SULAIMAN");
insert into karyawan(nik, nama) values("02598","M. TOHA RIDWAN");
insert into karyawan(nik, nama) values("02599","JAMIL B");
insert into karyawan(nik, nama) values("02600","MULIYATI");
insert into karyawan(nik, nama) values("02601","AJI SARWONO");
insert into karyawan(nik, nama) values("02602","SULTONI");
insert into karyawan(nik, nama) values("02603","SULAIMAN");
insert into karyawan(nik, nama) values("02604","LASMARI");
insert into karyawan(nik, nama) values("02605","NGADIARI");
insert into karyawan(nik, nama) values("02640","ISMAIL AFERO");
insert into karyawan(nik, nama) values("02641","ISMAIL");
insert into karyawan(nik, nama) values("02643","KARIYONO");
insert into karyawan(nik, nama) values("02696","BUDI UTOMO");
insert into karyawan(nik, nama) values("02708","CARITO");
insert into karyawan(nik, nama) values("02720","SUWITO");
insert into karyawan(nik, nama) values("02722","SUMARNO");
insert into karyawan(nik, nama) values("02723","SRI ASTUTIK");
insert into karyawan(nik, nama) values("02724","WACHID");
insert into karyawan(nik, nama) values("02725","MOHAMMAD SYAFII");
insert into karyawan(nik, nama) values("02726","SUWARNO");
insert into karyawan(nik, nama) values("02727","HARI EKO YULIANTO");
insert into karyawan(nik, nama) values("02728","MOCH. TAUFIK");
insert into karyawan(nik, nama) values("02729","SUGIANTO B.");
insert into karyawan(nik, nama) values("02750","KUSWARIYANTO");
insert into karyawan(nik, nama) values("02752","AMAS MASHUDIN");
insert into karyawan(nik, nama) values("02856","USMAN ALI");
insert into karyawan(nik, nama) values("02857","MOHAMMAD AFIF BASHORI");
insert into karyawan(nik, nama) values("02858","MUSLIMIN B");
insert into karyawan(nik, nama) values("02859","SUGENG");
insert into karyawan(nik, nama) values("02948","IMAM KHANAFI");
insert into karyawan(nik, nama) values("02958","SYAIFUL MALIK");
insert into karyawan(nik, nama) values("02959","CIHUSAN");
insert into karyawan(nik, nama) values("02980","NAAM");
insert into karyawan(nik, nama) values("02981","MUCHAMMAD KHOLIL");
insert into karyawan(nik, nama) values("02983","TAUFIK HIDAYAT");
insert into karyawan(nik, nama) values("02984","SUWANDI");
insert into karyawan(nik, nama) values("02985","MUHAMAD YUSUF");
insert into karyawan(nik, nama) values("02986","M. ARIFIN");
insert into karyawan(nik, nama) values("02987","M. HUSNI ARIF");
insert into karyawan(nik, nama) values("02990","TAMURI");
insert into karyawan(nik, nama) values("02991","PUJIONO");
insert into karyawan(nik, nama) values("02992","NUR SALIM");
insert into karyawan(nik, nama) values("02993","TAUFIK HIDAYAT");
insert into karyawan(nik, nama) values("02994","HARIYANTO");
insert into karyawan(nik, nama) values("02995","SUTARJO");
insert into karyawan(nik, nama) values("02996","YUWONO");
insert into karyawan(nik, nama) values("02997","PURNOMO HIDAYAT");
insert into karyawan(nik, nama) values("03160","BASHORI");
insert into karyawan(nik, nama) values("03319","NAIM");
insert into karyawan(nik, nama) values("03321","MUALIM");
insert into karyawan(nik, nama) values("03322","AGUS SALIM");
insert into karyawan(nik, nama) values("03323","KARNAWAN");
insert into karyawan(nik, nama) values("03324","PUJIONO C.");
insert into karyawan(nik, nama) values("03325","KANAPI");
insert into karyawan(nik, nama) values("03326","ROMLI");
insert into karyawan(nik, nama) values("03327","AHMAD AMROZI");
insert into karyawan(nik, nama) values("03329","EDI KARTONO");
insert into karyawan(nik, nama) values("03330","SOKHIB");
insert into karyawan(nik, nama) values("03332","WIJAYADI");
insert into karyawan(nik, nama) values("03335","SAIFUR RAHMAN");
insert into karyawan(nik, nama) values("03338","DIDIK AMANILLAH");
insert into karyawan(nik, nama) values("03339","WIWIK KUSRINI");
insert into karyawan(nik, nama) values("03340","DARIMUN");
insert into karyawan(nik, nama) values("03341","SAMPIR SUPRIONO");
insert into karyawan(nik, nama) values("03342","SOLEH C.");
insert into karyawan(nik, nama) values("03345","AHMAD ANSORI");
insert into karyawan(nik, nama) values("03347","SUTRISNO A.");
insert into karyawan(nik, nama) values("03349","NURUL ASIYAH");
insert into karyawan(nik, nama) values("03350","DULASIM");
insert into karyawan(nik, nama) values("03351","SLAMET RIYADI");
insert into karyawan(nik, nama) values("03356","AMININ");
insert into karyawan(nik, nama) values("03357","SUNADI");
insert into karyawan(nik, nama) values("03358","AKHIYAR");
insert into karyawan(nik, nama) values("03359","MUJIONO");
insert into karyawan(nik, nama) values("03362","FILLUN");
insert into karyawan(nik, nama) values("03365","SISWOKO");
insert into karyawan(nik, nama) values("03366","KOMARI");
insert into karyawan(nik, nama) values("03367","DANUN");
insert into karyawan(nik, nama) values("03374","SOLICHIN");
insert into karyawan(nik, nama) values("03375","SAMUJI");
insert into karyawan(nik, nama) values("03376","SUCIPTO A");
insert into karyawan(nik, nama) values("03377","YASAK");
insert into karyawan(nik, nama) values("03378","SATUKAN");
insert into karyawan(nik, nama) values("03381","ROKHIM");
insert into karyawan(nik, nama) values("03383","ABD. HAMID");
insert into karyawan(nik, nama) values("03384","MISKANAH NASIBIYANTI");
insert into karyawan(nik, nama) values("03385","KHODIJAH");
insert into karyawan(nik, nama) values("03386","TUNIK");
insert into karyawan(nik, nama) values("03388","ACHMAD TOSIN");
insert into karyawan(nik, nama) values("03389","NUR ALI C");
insert into karyawan(nik, nama) values("03390","SUNARJOKO");
insert into karyawan(nik, nama) values("03391","MOCH. YULIANTO BASORI");
insert into karyawan(nik, nama) values("03392","WAHYUDI");
insert into karyawan(nik, nama) values("03393","MOCHAMMAD MACHIN");
insert into karyawan(nik, nama) values("03394","AGUS SALIM");
insert into karyawan(nik, nama) values("03395","DASUN");
insert into karyawan(nik, nama) values("03397","CHAMIM");
insert into karyawan(nik, nama) values("03398","SUGENG ARIADI");
insert into karyawan(nik, nama) values("03401","ABDUL MUIN");
insert into karyawan(nik, nama) values("03402","MUSLICH");
insert into karyawan(nik, nama) values("03403","HADI MULYANTO");
insert into karyawan(nik, nama) values("03404","ABDUL KHOLIQ");
insert into karyawan(nik, nama) values("03405","NALAM");
insert into karyawan(nik, nama) values("03406","RIATSIH");
insert into karyawan(nik, nama) values("03407","TUTIK NINGSIH");
insert into karyawan(nik, nama) values("03408","SUMARI");
insert into karyawan(nik, nama) values("03410","FITRI SOESILOWATI");
insert into karyawan(nik, nama) values("03411","DALI");
insert into karyawan(nik, nama) values("03412","SOPINGI");
insert into karyawan(nik, nama) values("03413","ZAENAL ARIFIN");
insert into karyawan(nik, nama) values("03414","SUCIPTO");
insert into karyawan(nik, nama) values("03415","SUMIASIH");
insert into karyawan(nik, nama) values("03416","SUBANDI");
insert into karyawan(nik, nama) values("03421","IMAM KANAFI");
insert into karyawan(nik, nama) values("03423","LAMAD");
insert into karyawan(nik, nama) values("03424","DIDIK MARHENDRA WIJIWISNU KUNCARA  Ir");
insert into karyawan(nik, nama) values("03426","WAKIDI B");
insert into karyawan(nik, nama) values("03427","AKHWAN");
insert into karyawan(nik, nama) values("03433","SUEM");
insert into karyawan(nik, nama) values("03434","KAMSUNI");
insert into karyawan(nik, nama) values("03435","NUR ALI A");
insert into karyawan(nik, nama) values("03437","PUJIONO D.");
insert into karyawan(nik, nama) values("03438","KHOLIS YULIATI");
insert into karyawan(nik, nama) values("03439","MUHAMMAD ROIS");
insert into karyawan(nik, nama) values("03440","PUTUT PRAMONO");
insert into karyawan(nik, nama) values("03441","WIJIASIH");
insert into karyawan(nik, nama) values("03442","SUSIYATI");
insert into karyawan(nik, nama) values("03443","SITI KHORIYAH");
insert into karyawan(nik, nama) values("03444","YULIATI");
insert into karyawan(nik, nama) values("03445","SUDARTI");
insert into karyawan(nik, nama) values("03446","ROCHIMI");
insert into karyawan(nik, nama) values("03448","SUKANDAR");
insert into karyawan(nik, nama) values("03449","ZAINAL EFENDI");
insert into karyawan(nik, nama) values("03450","YAKUR");
insert into karyawan(nik, nama) values("03451","WIWIK WIJAYA");
insert into karyawan(nik, nama) values("03452","BAMBANG WIRIONO");
insert into karyawan(nik, nama) values("03453","RIYAMA SUSANTI");
insert into karyawan(nik, nama) values("03454","M. SYAFAK");
insert into karyawan(nik, nama) values("03455","KARTONO");
insert into karyawan(nik, nama) values("03456","ROCHMAD");
insert into karyawan(nik, nama) values("03457","MUKLHIS C.");
insert into karyawan(nik, nama) values("03458","NURSIATI");
insert into karyawan(nik, nama) values("03459","JUARI B.");
insert into karyawan(nik, nama) values("03462","NUR WAHYUNIATI");
insert into karyawan(nik, nama) values("03463","SUGIANTO");
insert into karyawan(nik, nama) values("03464","MISLAN");
insert into karyawan(nik, nama) values("03465","KARTONO A");
insert into karyawan(nik, nama) values("03466","SAMSURI");
insert into karyawan(nik, nama) values("03469","AKHMAD SUBIYANTONO");
insert into karyawan(nik, nama) values("03470","MOCH. ISTADZ ARISTA");
insert into karyawan(nik, nama) values("03471","DURASIM");
insert into karyawan(nik, nama) values("03583","ANDANGKARA PAMUNGKAS SUWANDARU");
insert into karyawan(nik, nama) values("03843","SURYADI");
insert into karyawan(nik, nama) values("03844","PURWANTO");
insert into karyawan(nik, nama) values("03846","RUDI HARTONO");
insert into karyawan(nik, nama) values("03847","AGUS SUNTORO");
insert into karyawan(nik, nama) values("03848","MUHAMAT SAMSUL");
insert into karyawan(nik, nama) values("03849","SUDARTO");
insert into karyawan(nik, nama) values("04224","ELISABETH MARIA ONG LEY KUN");
insert into karyawan(nik, nama) values("04373","EKO PUJIANTORO");
insert into karyawan(nik, nama) values("04375","NONOT SUGIHARTO");
insert into karyawan(nik, nama) values("04413","AHMAD FAUZIY");
insert into karyawan(nik, nama) values("04430","SOETJI HARIATI");
insert into karyawan(nik, nama) values("04519","HERI SUSANTO");
insert into karyawan(nik, nama) values("04520","SUBIYANTO");
insert into karyawan(nik, nama) values("04521","ACHMAD NUR HADI");
insert into karyawan(nik, nama) values("04522","YAJI");
insert into karyawan(nik, nama) values("04523","ROZIKIN");
insert into karyawan(nik, nama) values("04524","DAIMAM");
insert into karyawan(nik, nama) values("04528","IMRON B.");
insert into karyawan(nik, nama) values("04529","MUKHAMMAD SHOLEH");
insert into karyawan(nik, nama) values("04531","MOCH. SYAIFUL");
insert into karyawan(nik, nama) values("04532","KESTIANTOMO");
insert into karyawan(nik, nama) values("04533","HADI PRABOWO");
insert into karyawan(nik, nama) values("04535","NUR HASAN");
insert into karyawan(nik, nama) values("04536","MUSTAIN");
insert into karyawan(nik, nama) values("04537","BAMBANG SUROSO");
insert into karyawan(nik, nama) values("04673","KUSNANIWOTO");
insert into karyawan(nik, nama) values("04704","ACHMAD NASIRUDDIN MUSTOFA");
insert into karyawan(nik, nama) values("04705","USMAN EFENDI");
insert into karyawan(nik, nama) values("04706","DIDIK MUJAYADI");
insert into karyawan(nik, nama) values("04707","MUHAMMAD YUSUF");
insert into karyawan(nik, nama) values("04754","MOCHAMMAD MUIN");
insert into karyawan(nik, nama) values("04897","SUROSO HADI PRAYITNO");
insert into karyawan(nik, nama) values("04930","MOHAMMAD ANTON");
insert into karyawan(nik, nama) values("04936","WARLIN EFENDI");
insert into karyawan(nik, nama) values("05133","MULYANTO");
insert into karyawan(nik, nama) values("05135","SYAIFUL ANWAR");
insert into karyawan(nik, nama) values("05136","LUKMAN HAKIM");
insert into karyawan(nik, nama) values("05137","M. SYAIFUL HAMAM");
insert into karyawan(nik, nama) values("05144","SUWIKNYO");
insert into karyawan(nik, nama) values("05162","RUDY PILU HANTORO");
insert into karyawan(nik, nama) values("05163","AGUS RIANTO");
insert into karyawan(nik, nama) values("05213","ANDRIE SURYAWIJAYA  ST");
insert into karyawan(nik, nama) values("05214","ANDI KURNIAWAN");
insert into karyawan(nik, nama) values("05411","NOOR HIDAYAT  ST");
insert into karyawan(nik, nama) values("05484","JOKO WIDODO");
insert into karyawan(nik, nama) values("05501","NANIK NARIYATI");
insert into karyawan(nik, nama) values("05514","NOWO SETYO BUDI");
insert into karyawan(nik, nama) values("05544","HARI UTOMO");
insert into karyawan(nik, nama) values("05551","WARIFIN");
insert into karyawan(nik, nama) values("05585","SENEDI");
insert into karyawan(nik, nama) values("05731","LINDAWATI");
insert into karyawan(nik, nama) values("05743","INDRA SETYOWATI");
insert into karyawan(nik, nama) values("05962","ABDUL AZIZ");
insert into karyawan(nik, nama) values("06052","ERY SETYOWATI");
insert into karyawan(nik, nama) values("06065","SOLEH");
insert into karyawan(nik, nama) values("06184","KASAN BISRI");
insert into karyawan(nik, nama) values("06205","SUGIANTO");
insert into karyawan(nik, nama) values("06330","WAGI");
insert into karyawan(nik, nama) values("06331","MAWAN DARMAWAN");
insert into karyawan(nik, nama) values("06332","NURIADI");
insert into karyawan(nik, nama) values("06336","M. SAKRI");
insert into karyawan(nik, nama) values("06337","ERWANDI");
insert into karyawan(nik, nama) values("06362","SUDARMAJI");
insert into karyawan(nik, nama) values("06368","IRWANTO");
insert into karyawan(nik, nama) values("06370","NURIYANTO");
insert into karyawan(nik, nama) values("06371","SUBUH SUHONO");
insert into karyawan(nik, nama) values("06386","ACH. FAUZI");
insert into karyawan(nik, nama) values("06387","ANTONIUS ARI W");
insert into karyawan(nik, nama) values("06388","BAMBANG DEWANTO");
insert into karyawan(nik, nama) values("06389","SLAMET");
insert into karyawan(nik, nama) values("06392","ENI FATHIYAH");
insert into karyawan(nik, nama) values("06401","WUJUD SLAMET");
insert into karyawan(nik, nama) values("06415","MOH. ARIFIN");
insert into karyawan(nik, nama) values("06416","RUDIN");
insert into karyawan(nik, nama) values("06420","BUDIONO");
insert into karyawan(nik, nama) values("06421","SUCIPTO");
insert into karyawan(nik, nama) values("06426","DEDY RAHARJO");
insert into karyawan(nik, nama) values("06447","SITI ROCHMAWATI");
insert into karyawan(nik, nama) values("06448","RANTI BAHAGIA TRISNAWATI");
insert into karyawan(nik, nama) values("06449","SUTEJO PURNOMO");
insert into karyawan(nik, nama) values("06450","ITA SUGIATI");
insert into karyawan(nik, nama) values("06451","NACHROWI");
insert into karyawan(nik, nama) values("06452","SANDY ALIEF");
insert into karyawan(nik, nama) values("06453","YULAIKHAH");
insert into karyawan(nik, nama) values("06457","SULASTRI");
insert into karyawan(nik, nama) values("06467","SUGIONO");
insert into karyawan(nik, nama) values("06474","IRA MAYANG SARI");
insert into karyawan(nik, nama) values("06477","NURSALIM");
insert into karyawan(nik, nama) values("06479","JUMIDAH");
insert into karyawan(nik, nama) values("06482","YOYOK IRAWAN");
insert into karyawan(nik, nama) values("06484","CATRI WINARSIH");
insert into karyawan(nik, nama) values("06485","MUHAMMAD YUSTADO");
insert into karyawan(nik, nama) values("06486","WIWIT AGUSTINAH");
insert into karyawan(nik, nama) values("06496","TARMUJI");
insert into karyawan(nik, nama) values("06497","SOKHIBUL HUDA");
insert into karyawan(nik, nama) values("06547","M. YASIN FITRAYAH");
insert into karyawan(nik, nama) values("06548","AGUS SETYO RUDI");
insert into karyawan(nik, nama) values("06549","BAMBANG EDI SUPRAPTO");
insert into karyawan(nik, nama) values("06550","SLAMET SHOKIB");
insert into karyawan(nik, nama) values("06551","MOKHAMMAD FADHOLI");
insert into karyawan(nik, nama) values("06552","YUDIANTO");
insert into karyawan(nik, nama) values("06553","HARIYONO");
insert into karyawan(nik, nama) values("06554","SUHARSONO");
insert into karyawan(nik, nama) values("06556","WIWIT MULYANTO");
insert into karyawan(nik, nama) values("06558","BUDI SANTOSO");
insert into karyawan(nik, nama) values("06560","TAUFIK HIDAYAT");
insert into karyawan(nik, nama) values("06561","ARIS SUGIONO");
insert into karyawan(nik, nama) values("06584","JOKO SANTOSO");
insert into karyawan(nik, nama) values("06585","RISDIAN ADI W.");
insert into karyawan(nik, nama) values("06586","WIWIK SUGIANTI");
insert into karyawan(nik, nama) values("06681","SARIYONO");
insert into karyawan(nik, nama) values("06691","YENI DIAN ARTHARINA");
insert into karyawan(nik, nama) values("06693","AMIN SUPRIANTO");
insert into karyawan(nik, nama) values("06694","SUHARTINI FIRGINA");
insert into karyawan(nik, nama) values("06704","BUDI ASMORO");
insert into karyawan(nik, nama) values("06705","MIKO HANDRY");
insert into karyawan(nik, nama) values("06706","HERMAN SUSILO");
insert into karyawan(nik, nama) values("06708","JASMONO");
insert into karyawan(nik, nama) values("06709","ROFII");
insert into karyawan(nik, nama) values("06710","ARIF RACHMAN");
insert into karyawan(nik, nama) values("06722","AGUS SUSANTO");
insert into karyawan(nik, nama) values("06723","RUDI HANDOYO");
insert into karyawan(nik, nama) values("06725","RAMELAN");
insert into karyawan(nik, nama) values("06726","DIDIN AFRIANTO");
insert into karyawan(nik, nama) values("06735","KRISDI WIYANTO");
insert into karyawan(nik, nama) values("06801","DIH WAHYU RIANTO");
insert into karyawan(nik, nama) values("06803","DIDIK HARI SETIAWAN");
insert into karyawan(nik, nama) values("06886","ZAENAL ARIFIN");
insert into karyawan(nik, nama) values("06887","WAHYUDI SISWO SAPUTRO");
insert into karyawan(nik, nama) values("06891","ULFA HAYANTI");
insert into karyawan(nik, nama) values("06892","DWI RETNO WIDIYASTATIK");
insert into karyawan(nik, nama) values("06894","ABDILLAH NURHUDA");
insert into karyawan(nik, nama) values("06895","BUDI SANTOSO");
insert into karyawan(nik, nama) values("06896","MOKHAMMAD MUKHDORI");
insert into karyawan(nik, nama) values("06898","IBNU ANAS");
insert into karyawan(nik, nama) values("06899","ABDUL HAMID");
insert into karyawan(nik, nama) values("06946","DIDIK AGUS PRIYANTO");
insert into karyawan(nik, nama) values("06948","TAUFIK ARIYANTO");
insert into karyawan(nik, nama) values("06950","RENY INDRIANI");
insert into karyawan(nik, nama) values("06982","HADY PRAYOGO");
insert into karyawan(nik, nama) values("06985","YANTI DYAH LESTARI");
insert into karyawan(nik, nama) values("06986","USULUDIN");
insert into karyawan(nik, nama) values("06988","SITI AMINAH");
insert into karyawan(nik, nama) values("06989","SYARIFUDIN");
insert into karyawan(nik, nama) values("06990","ACHMAD SHOLEH");
insert into karyawan(nik, nama) values("07002","DIDIK WIDI SUCAHYO");
insert into karyawan(nik, nama) values("07026","IWAN KRESNA");
insert into karyawan(nik, nama) values("07027","ARIONO SETIAWAN");
insert into karyawan(nik, nama) values("07029","APIT SUPRAYITNO");
insert into karyawan(nik, nama) values("07040","SELAMET SUTRISNO");
insert into karyawan(nik, nama) values("07046","TAUFIQ");
insert into karyawan(nik, nama) values("07047","SURYANTO");
insert into karyawan(nik, nama) values("07048","SYAIFUL ROHMAN");
insert into karyawan(nik, nama) values("07049","NUKI");
insert into karyawan(nik, nama) values("07050","BAMBANG SUPRIYANTO");
insert into karyawan(nik, nama) values("07059","SRIATININGSIH");
insert into karyawan(nik, nama) values("07068","SOLIKHIN");
insert into karyawan(nik, nama) values("07069","DICKY PRATANTO  ST");
insert into karyawan(nik, nama) values("07128","MASHUDA");
insert into karyawan(nik, nama) values("07129","SAIFUL ANAM");
insert into karyawan(nik, nama) values("07130","JOKO PURNOMO");
insert into karyawan(nik, nama) values("07131","SITI JULAIKHAH");
insert into karyawan(nik, nama) values("07133","TANTO SLAMET");
insert into karyawan(nik, nama) values("07140","HIDAYAT");
insert into karyawan(nik, nama) values("07151","SOPII");
insert into karyawan(nik, nama) values("07170","TRI PRASETYO");
insert into karyawan(nik, nama) values("07171","SULAIMAN");
insert into karyawan(nik, nama) values("07180","SAKRI");
insert into karyawan(nik, nama) values("07199","KASIYANTO");
insert into karyawan(nik, nama) values("07232","SETIOWATI");
insert into karyawan(nik, nama) values("07270","ABDUL CHOIRUL");
insert into karyawan(nik, nama) values("07504","MINTO PRASETYO");
insert into karyawan(nik, nama) values("07537","DIDIK PRASETYO VINCENSIUS");
insert into karyawan(nik, nama) values("07690","M. YUDHI SYARIFUDDIN  ST");
insert into karyawan(nik, nama) values("07717","NUR ASIH");
insert into karyawan(nik, nama) values("07778","BAMBANG SUGIARTO");
insert into karyawan(nik, nama) values("07955","SUDARMAJI");
insert into karyawan(nik, nama) values("07956","ABD. GHOFUR");
insert into karyawan(nik, nama) values("07957","MUKHIDIN");
insert into karyawan(nik, nama) values("07959","SETYO WAHYUDI");
insert into karyawan(nik, nama) values("07960","MUHAMMAD KHOIRUL");
insert into karyawan(nik, nama) values("07961","MOCHAMAD SAMPURNO");
insert into karyawan(nik, nama) values("07962","MUHAMMAD MAHFUD");
insert into karyawan(nik, nama) values("07975","TOTOK BASUKI RACHMAD");
insert into karyawan(nik, nama) values("07990","PURNOMO SIGIT");
insert into karyawan(nik, nama) values("08166","JURITO");
insert into karyawan(nik, nama) values("08181","ARI WIJIANTO");
insert into karyawan(nik, nama) values("08222","SUSANTO");
insert into karyawan(nik, nama) values("08224","SAIFUDIN ZUHRI");
insert into karyawan(nik, nama) values("08302","NANANG SUWITO  ST");
insert into karyawan(nik, nama) values("08303","I MADE OKA SOPHIA D. S.");
insert into karyawan(nik, nama) values("08307","REDY MARDIYANTO");
insert into karyawan(nik, nama) values("08311","SUHADAK ARIEF");
insert into karyawan(nik, nama) values("08313","HARIYANTO");
insert into karyawan(nik, nama) values("08314","ACH. SAIFUL");
insert into karyawan(nik, nama) values("08337","MOH. FARID SAUQI");
insert into karyawan(nik, nama) values("08340","SUCAHYO");
insert into karyawan(nik, nama) values("08342","SETYO NURYANTO");
insert into karyawan(nik, nama) values("08349","ASFAR");
insert into karyawan(nik, nama) values("08351","FACHRUDIN ALI A.");
insert into karyawan(nik, nama) values("08352","SUTIKNO");
insert into karyawan(nik, nama) values("08363","MACHMUD");
insert into karyawan(nik, nama) values("08364","GATOT URIP W.");
insert into karyawan(nik, nama) values("08365","ANDREAS TEGUH HERMAWAN");
insert into karyawan(nik, nama) values("08366","WAJI");
insert into karyawan(nik, nama) values("08368","KHAFIT LUQMAN");
insert into karyawan(nik, nama) values("08372","SUHENDRI");
insert into karyawan(nik, nama) values("08373","SUGENG PRANOWO");
insert into karyawan(nik, nama) values("08377","KOMARUDIN");
insert into karyawan(nik, nama) values("08378","AKHMAD SYARONI");
insert into karyawan(nik, nama) values("08380","ONI SAMSUL BAHRI RAMLI");
insert into karyawan(nik, nama) values("08433","DWI ADI SUMAI");
insert into karyawan(nik, nama) values("08442","IKWAN PRIBADI");
insert into karyawan(nik, nama) values("08445","HARI KUSMIANTO");
insert into karyawan(nik, nama) values("08446","APRIYANTO HERRU WICAKSONO");
insert into karyawan(nik, nama) values("08447","SARI SETIAWAN");
insert into karyawan(nik, nama) values("08450","AGUS YUSRON");
insert into karyawan(nik, nama) values("08451","HERY PRASETYO");
insert into karyawan(nik, nama) values("08452","SYARIFUDIN");
insert into karyawan(nik, nama) values("08479","M. INWAN JAYADI");
insert into karyawan(nik, nama) values("08519","KHOIRUL MUSTAKIM");
insert into karyawan(nik, nama) values("08520","SURYA EDI");
insert into karyawan(nik, nama) values("08521","TAUFIQ FADRI HIDAYANTO");
insert into karyawan(nik, nama) values("08522","CHOIRUL ANWAR");
insert into karyawan(nik, nama) values("08524","SAIFUL");
insert into karyawan(nik, nama) values("08525","WAHYUDI");
insert into karyawan(nik, nama) values("08526","MOH. HIZAM");
insert into karyawan(nik, nama) values("08555","AGUS SUPRIONO");
insert into karyawan(nik, nama) values("08577","GAGUK SARWOKO  ST");
insert into karyawan(nik, nama) values("08614","RULIS HIDAYAT");
insert into karyawan(nik, nama) values("08615","LAURENSIUS JOHNY");
insert into karyawan(nik, nama) values("08662","YONG MAHARDIKA DWIPANA");
insert into karyawan(nik, nama) values("08696","MUHAMAD HADIYATULLAH");
insert into karyawan(nik, nama) values("08697","ABDUL FARID");
insert into karyawan(nik, nama) values("08716","DEDIK YUDHA P");
insert into karyawan(nik, nama) values("08754","MOHAMMAD YASIN");
insert into karyawan(nik, nama) values("08770","MUHAMMAD FATCHUR ROCHMAN");
insert into karyawan(nik, nama) values("08772","WAHYUDI");
insert into karyawan(nik, nama) values("08773","NGATIMAN");
insert into karyawan(nik, nama) values("08774","ADI PRIANA");
insert into karyawan(nik, nama) values("08776","SUHARJOYO");
insert into karyawan(nik, nama) values("08904","M. NURSOBARI SAKUR");
insert into karyawan(nik, nama) values("08906","SUGIONO HIDAYAT");
insert into karyawan(nik, nama) values("08929","MOCH. KHOLIL");
insert into karyawan(nik, nama) values("08930","NUR KASAN");
insert into karyawan(nik, nama) values("08931","SYARIFUDIN");
insert into karyawan(nik, nama) values("08933","THOMAS HERRY SISWANTO");
insert into karyawan(nik, nama) values("08935","AGUS ICHWANTO");
insert into karyawan(nik, nama) values("08936","ACHMAD ZAKARIYA");
insert into karyawan(nik, nama) values("08938","KISWOYO");
insert into karyawan(nik, nama) values("08983","AINUR ROFIQ");
insert into karyawan(nik, nama) values("09003","NUGROHO ADIWIJONO");
insert into karyawan(nik, nama) values("09004","MOHAMMAD TOHA MAUN");
insert into karyawan(nik, nama) values("09006","YOSEF SIMON EKO HADI SUBAGYO");
insert into karyawan(nik, nama) values("09042","AGUS WIDODO");
insert into karyawan(nik, nama) values("09045","ZAINURI");
insert into karyawan(nik, nama) values("09062","SUWANDI");
insert into karyawan(nik, nama) values("09078","MUCHAMMAD SAICHU");
insert into karyawan(nik, nama) values("09098","MARCELLINUS AGUNG ANDRI");
insert into karyawan(nik, nama) values("09101","MASUDI");
insert into karyawan(nik, nama) values("09102","HARTOYO");
insert into karyawan(nik, nama) values("09103","SUWANTO");
insert into karyawan(nik, nama) values("09104","MUMFASIL");
insert into karyawan(nik, nama) values("09106","EMANUEL EKO BUDI SANTOSO");
insert into karyawan(nik, nama) values("09125","WAHYUDI");
insert into karyawan(nik, nama) values("09131","BUDIONO");
insert into karyawan(nik, nama) values("09132","RUGIATI NINGSIH");
insert into karyawan(nik, nama) values("09134","PURNOMO WAHYU INDIANTO");
insert into karyawan(nik, nama) values("09137","KARIYANTO");
insert into karyawan(nik, nama) values("09145","ROISUL ULUM");
insert into karyawan(nik, nama) values("09146","RETNO ANI ASMORO");
insert into karyawan(nik, nama) values("09231","I PUTU TIRTAYASA");
insert into karyawan(nik, nama) values("09232","DWI SUYITNO UTOMO");
insert into karyawan(nik, nama) values("09235","ARIES PRIBADI");
insert into karyawan(nik, nama) values("09243","MARIA RISKA UMAMI");
insert into karyawan(nik, nama) values("09255","MULYONO");
insert into karyawan(nik, nama) values("09257","AGUS JUNAIDI");
insert into karyawan(nik, nama) values("09259","SUTOYO");
insert into karyawan(nik, nama) values("09274","AHMAD ARIFIN");
insert into karyawan(nik, nama) values("09276","ENDRO SUMARSONO");
insert into karyawan(nik, nama) values("09291","HANDOKO WISNU DJUMANTORO");
insert into karyawan(nik, nama) values("09307","HENRY HANDIANTO");
insert into karyawan(nik, nama) values("09372","HERY PURWANTO");
insert into karyawan(nik, nama) values("09517","NAFAN");
insert into karyawan(nik, nama) values("09519","WAHYUDI");
insert into karyawan(nik, nama) values("09637","EKO WAHYUDI");
insert into karyawan(nik, nama) values("09928","DWI MUKTIONO");
insert into karyawan(nik, nama) values("09929","DARTO");
insert into karyawan(nik, nama) values("09940","ROCHMAT TRI KUNCORO");
insert into karyawan(nik, nama) values("09942","KHARIS SYARIFUDHIN");
insert into karyawan(nik, nama) values("09943","DWI HARI SUTRISNO");
insert into karyawan(nik, nama) values("09945","ANANG DWI CAHYONO");
insert into karyawan(nik, nama) values("09946","HARIS FAUZI");
insert into karyawan(nik, nama) values("10023","NI PUTU AGUS YULIAWATI");
insert into karyawan(nik, nama) values("10057","SADAH FERIYATI");
insert into karyawan(nik, nama) values("10063","INDRA ARIS SETIAWAN");
insert into karyawan(nik, nama) values("10089","ACHMAD KHOSIM");
insert into karyawan(nik, nama) values("10214","ARDIAN HENDRA WIJAYA");
insert into karyawan(nik, nama) values("10340","ADI PURWANTO");
insert into karyawan(nik, nama) values("10341","SODIKIN");
insert into karyawan(nik, nama) values("10343","EKO YUDI ISWANTO");
insert into karyawan(nik, nama) values("10344","SHOLIHAN");
insert into karyawan(nik, nama) values("10345","HARI SETIAWAN");
insert into karyawan(nik, nama) values("10346","SAMSUL ARIFIN");
insert into karyawan(nik, nama) values("10347","KHOLILI");
insert into karyawan(nik, nama) values("10348","RICKI BUDI SETIAWAN");
insert into karyawan(nik, nama) values("10349","DEWI ASTUTI");
insert into karyawan(nik, nama) values("10350","ERVINA EMILSYAH");
insert into karyawan(nik, nama) values("10352","KIFLI");
insert into karyawan(nik, nama) values("10360","SRIYANI");
insert into karyawan(nik, nama) values("10361","MULYONO");
insert into karyawan(nik, nama) values("10364","MUSHILATUL KHABIBAH");
insert into karyawan(nik, nama) values("10376","ARIF TRI WINARNO");
insert into karyawan(nik, nama) values("10377","SUWARNO");
insert into karyawan(nik, nama) values("10378","SUSANTO");
insert into karyawan(nik, nama) values("10379","YUSUF KUSUMA");
insert into karyawan(nik, nama) values("10380","WIDODO");
insert into karyawan(nik, nama) values("10382","PITONO");
insert into karyawan(nik, nama) values("10383","MOCHAMAD ZULFA");
insert into karyawan(nik, nama) values("10384","IMAM MASHURI");
insert into karyawan(nik, nama) values("10397","SUMARTO");
insert into karyawan(nik, nama) values("10401","M. MUCTAR ARIFIN");
insert into karyawan(nik, nama) values("10402","SUGIONO");
insert into karyawan(nik, nama) values("10447","HARI YULIANTO");
insert into karyawan(nik, nama) values("10448","DIRAWANTO");
insert into karyawan(nik, nama) values("10449","AHMAD AFANDI");
insert into karyawan(nik, nama) values("10452","ARIK AWAN SUDJIANTO");
insert into karyawan(nik, nama) values("10453","MOHAMMAD IHWAN SYARONI");
insert into karyawan(nik, nama) values("10455","HERU WIDODO");
insert into karyawan(nik, nama) values("10456","ADI PRAYITNO");
insert into karyawan(nik, nama) values("10457","NASARI");
insert into karyawan(nik, nama) values("10477","AGUS RIFFAI");
insert into karyawan(nik, nama) values("10479","AGUS PURWANTO");
insert into karyawan(nik, nama) values("10480","SAMSUL ARIFIN");
insert into karyawan(nik, nama) values("10481","CUNG SUPRIADI");
insert into karyawan(nik, nama) values("10485","TOTOK SOENARDI");
insert into karyawan(nik, nama) values("10488","YOHANES WANAJI");
insert into karyawan(nik, nama) values("10489","MULYADI");
insert into karyawan(nik, nama) values("10490","MUAMAR ZAEN");
insert into karyawan(nik, nama) values("10494","IWAN SETIAWAN");
insert into karyawan(nik, nama) values("10597","TEGUH ARFIANTO");
insert into karyawan(nik, nama) values("10598","SUWITO");
insert into karyawan(nik, nama) values("10604","DIDIK KRISWANDI");
insert into karyawan(nik, nama) values("10628","ABDUL ROSID");
insert into karyawan(nik, nama) values("10629","NURCHOLIS");
insert into karyawan(nik, nama) values("10763","SUTIKNO");
insert into karyawan(nik, nama) values("10771","SHOKIB");
insert into karyawan(nik, nama) values("10772","YUNUS SUGIANTO");
insert into karyawan(nik, nama) values("10802","ARDI IRAWAN");
insert into karyawan(nik, nama) values("10804","SUYANTO");
insert into karyawan(nik, nama) values("10992","MUJI LESTARI");
insert into karyawan(nik, nama) values("11119","DYAN STYANTO PRASOJO");
insert into karyawan(nik, nama) values("11120","SUPRIYANTO");
insert into karyawan(nik, nama) values("11122","HENDRA YULIANTO");
insert into karyawan(nik, nama) values("11157","ACHMAD AFANDI");
insert into karyawan(nik, nama) values("11175","SUMARI");
insert into karyawan(nik, nama) values("11178","EKO SUGITO");
insert into karyawan(nik, nama) values("11179","CHODIRIN");
insert into karyawan(nik, nama) values("11181","PANTJA PRIANTO");
insert into karyawan(nik, nama) values("11207","IWAN SETIAWAN");
insert into karyawan(nik, nama) values("11213","M SYARIFUDIN JAMAL");
insert into karyawan(nik, nama) values("11214","MOH SAID");
insert into karyawan(nik, nama) values("11215","HERI WIRATNO");
insert into karyawan(nik, nama) values("11216","ADI DIANSYAH");
insert into karyawan(nik, nama) values("11217","MOHAMAD GHOFAR");
insert into karyawan(nik, nama) values("11238","IDA BAGUS KADE ADNYANA PUTRA");
insert into karyawan(nik, nama) values("11247","MOCH IBADY MARUF");
insert into karyawan(nik, nama) values("11249","TASRIP");
insert into karyawan(nik, nama) values("11250","FINARNI ROSSALINDA");
insert into karyawan(nik, nama) values("11251","HERNAWAN NURDIYANTO  ST");
insert into karyawan(nik, nama) values("11299","YUNAINI");
insert into karyawan(nik, nama) values("11307","AGUS SOLEHKHUDIN");
insert into karyawan(nik, nama) values("11359","LISA PARDIANA");
insert into karyawan(nik, nama) values("11388","WIWIK SUNARSIH");
insert into karyawan(nik, nama) values("11820","SAPTO ADI TRIATMOJO");
insert into karyawan(nik, nama) values("12272","AGUNG ARIWIBOWO");
insert into karyawan(nik, nama) values("12273","EDDY SANTOSO");
insert into karyawan(nik, nama) values("12274","HARIYADI");
insert into karyawan(nik, nama) values("12275","MUHAMMAD MUJIB");
insert into karyawan(nik, nama) values("12276","MUHAMMAD SHOLEH");
insert into karyawan(nik, nama) values("12277","SAMSUL ARIFIN");
insert into karyawan(nik, nama) values("12278","SUGENG MARDIANTO");
insert into karyawan(nik, nama) values("12323","TITIK INDARTI");
insert into karyawan(nik, nama) values("12324","SUPRIYONO");
insert into karyawan(nik, nama) values("12359","ZAINUL ABIDIN");
insert into karyawan(nik, nama) values("12690","YODI KAMISWARA");
insert into karyawan(nik, nama) values("12803","FAFIT RAHMAT AJI");
insert into karyawan(nik, nama) values("12804","MAHFUD");
insert into karyawan(nik, nama) values("12805","ACHMAD YONO");
insert into karyawan(nik, nama) values("12806","IRWAN ARIF EFFENDI  SE");
insert into karyawan(nik, nama) values("13346","RONY TIMPORWANTO");
insert into karyawan(nik, nama) values("13348","ZAINUL FAIZIN");
insert into karyawan(nik, nama) values("13349","SUPONO");
insert into karyawan(nik, nama) values("13350","FEMBER HARRY WIBOWO");
insert into karyawan(nik, nama) values("13351","AGUS SUPRIANTONO");
insert into karyawan(nik, nama) values("13354","MUHAMMAD GIGIH");
insert into karyawan(nik, nama) values("13355","MUKHAMAD IMAM FATONI");
insert into karyawan(nik, nama) values("13356","KATUWI SAMSUL RIZAL");
insert into karyawan(nik, nama) values("13357","MOHAMMAD BASORI ALWI");
insert into karyawan(nik, nama) values("13718","PURWANTO");
insert into karyawan(nik, nama) values("13719","SUDARMANTO");
insert into karyawan(nik, nama) values("13723","SUPRIYANTO");
insert into karyawan(nik, nama) values("13726","WIJI DWI KUSDIANTO");
insert into karyawan(nik, nama) values("13728","ANTON SUJARWO");
insert into karyawan(nik, nama) values("13730","ARIF RAKHMAN");
insert into karyawan(nik, nama) values("13874","NIKHO YANUAR ADAM");
insert into karyawan(nik, nama) values("13876","ANDIK SUYANTO");
insert into karyawan(nik, nama) values("13878","RICKY MARENDRA  SH");
insert into karyawan(nik, nama) values("13879","ARI FAJAR WAHYUDI");
insert into karyawan(nik, nama) values("13887","AKMAD ARIF ZAINUDIN");
insert into karyawan(nik, nama) values("13888","JOKO WAHYUNARTO");
insert into karyawan(nik, nama) values("13889","BUDI SANTOSO");
insert into karyawan(nik, nama) values("13891","MUKHAMAD WAHYUDI");
insert into karyawan(nik, nama) values("13896","WAHYUDI");
insert into karyawan(nik, nama) values("13901","ARIF SUMANTO");
insert into karyawan(nik, nama) values("13902","VICKY FAHMI HATMA PERDANA");
insert into karyawan(nik, nama) values("13903","AMIN SUSILO");
insert into karyawan(nik, nama) values("13906","YOVI KURNIAWAN PUTRA");
insert into karyawan(nik, nama) values("13909","SIGIT KURNIAWAN");
insert into karyawan(nik, nama) values("13915","PRAWIRA ADI SANJAYA  STP");
insert into karyawan(nik, nama) values("13937","DWI NINDRA TIMORIAWAN");
insert into karyawan(nik, nama) values("13939","BACHTIAR EFFENDY");
insert into karyawan(nik, nama) values("13942","SLAMET BUDI RAHARJO");
insert into karyawan(nik, nama) values("13948","ALFAN");
insert into karyawan(nik, nama) values("14021","NURULHUDIN");
insert into karyawan(nik, nama) values("14030","MOCH. DAHILUN ULUM");
insert into karyawan(nik, nama) values("14031","MUNTOHAR");
insert into karyawan(nik, nama) values("14084","WIWIN NIRWANI WIRAWAN");
insert into karyawan(nik, nama) values("14085","YAYUK SRI RAHAYU");
insert into karyawan(nik, nama) values("14086","YANTI MAYANGSARI");
insert into karyawan(nik, nama) values("14088","MARTHA YENDRA SARI WAHYUNINGSIH");
insert into karyawan(nik, nama) values("14089","ERNAWATI EFENDI");
insert into karyawan(nik, nama) values("14090","SUNARMI");
insert into karyawan(nik, nama) values("14164","DWI CAHYO SAPUTRO");
insert into karyawan(nik, nama) values("14165","BADAY QURBANI");
insert into karyawan(nik, nama) values("14405","YUTI SUHARIYANI");
insert into karyawan(nik, nama) values("14474","YOHAN MAI PRASSETIA");
insert into karyawan(nik, nama) values("14992","PAULUS YUYUN SETYOHANDOKO");
insert into karyawan(nik, nama) values("15149","MOHAMMAD ASROFI");
insert into karyawan(nik, nama) values("15340","YUDHA HERTANTO");
insert into karyawan(nik, nama) values("15397","SUWARNO");
insert into karyawan(nik, nama) values("15402","YOGA MAULANA");
insert into karyawan(nik, nama) values("15494","PAULUS ERY PRAMUDITO");
insert into karyawan(nik, nama) values("15731","MUHAMMAD MUHDLOR");
insert into karyawan(nik, nama) values("15822","DIDIT EKO LESMONO");
insert into karyawan(nik, nama) values("15823","BAHTIAR ROMADHON");
insert into karyawan(nik, nama) values("15845","AGUS HARIYANTO");
insert into karyawan(nik, nama) values("15846","MASUD HANIFAN");
insert into karyawan(nik, nama) values("15909","HERU DWIYANTO");
insert into karyawan(nik, nama) values("15910","IBNU HARYONO");
insert into karyawan(nik, nama) values("16046","ERNA MERY SILFIA DEWI");
insert into karyawan(nik, nama) values("16063","ASRI ROBY CAHYONO");
insert into karyawan(nik, nama) values("16090","RISKA WAHYU NIRMALASARI");
insert into karyawan(nik, nama) values("16168","MUHAMMAD IMRON");
insert into karyawan(nik, nama) values("16201","AHMAD JUNAIDI");
insert into karyawan(nik, nama) values("16257","ABDUL ROHMAN");
insert into karyawan(nik, nama) values("16300","ANDIK DWI PURNOMO");
insert into karyawan(nik, nama) values("16301","LASMANA KUSROMADHONI");
insert into karyawan(nik, nama) values("16329","SELVI SETYOWATI");
insert into karyawan(nik, nama) values("16330","UNIK RACHMAWATI");
insert into karyawan(nik, nama) values("16383","SYAMSUL HUDHA");
insert into karyawan(nik, nama) values("16401","SUYANTO HADI PRANOTO");
insert into karyawan(nik, nama) values("16403","ACHMAD DJAINURI");
insert into karyawan(nik, nama) values("16481","ARY HASANUDDIN");
insert into karyawan(nik, nama) values("16621","AGUNG CAHYO ADI");
insert into karyawan(nik, nama) values("16857","CHOIRON");
insert into karyawan(nik, nama) values("16858","HERTA SUGIARTO");
insert into karyawan(nik, nama) values("16859","DJAROT SUMITRO");
insert into karyawan(nik, nama) values("16860","SUMARTONO");
insert into karyawan(nik, nama) values("16862","TAUFIQ ROHMAN");
insert into karyawan(nik, nama) values("16891","MAKHMUD MUHAMMAD");
insert into karyawan(nik, nama) values("17287","TOMI WIDJAYA");
insert into karyawan(nik, nama) values("17288","FIJANARKO");
insert into karyawan(nik, nama) values("17289","KALDI UTOMO");
insert into karyawan(nik, nama) values("17290","ACHMAD ASARI");
insert into karyawan(nik, nama) values("17291","BASUKI");
insert into karyawan(nik, nama) values("17292","SLAMET AFIFUDIN");
insert into karyawan(nik, nama) values("17293","KRISTIANTO");
insert into karyawan(nik, nama) values("17294","SAMSUL ARIFIN");
insert into karyawan(nik, nama) values("17295","FENI PRASETYO");
insert into karyawan(nik, nama) values("17296","LEXY LEKSMONO PUTRANTO");
insert into karyawan(nik, nama) values("17297","USMAN SADARWANTO");
insert into karyawan(nik, nama) values("17298","KIKI PRAYOGO");
insert into karyawan(nik, nama) values("17299","SOLIKHA");
insert into karyawan(nik, nama) values("17300","HARIANTO");
insert into karyawan(nik, nama) values("17301","AHMAD SAYFUDDIN");
insert into karyawan(nik, nama) values("17302","EDI SETYO WASONO");
insert into karyawan(nik, nama) values("17303","EKA HERI PURWANTI");
insert into karyawan(nik, nama) values("17305","NUKY LICFAN GANDA MANA");
insert into karyawan(nik, nama) values("17306","HENDIK SETIAWAN");
insert into karyawan(nik, nama) values("17307","AGUS PURNOMO");
insert into karyawan(nik, nama) values("17336","MUKHAMAD SAIKHU");
insert into karyawan(nik, nama) values("17337","SUDARSONO");
insert into karyawan(nik, nama) values("17338","EKO WAHYUDIONO");
insert into karyawan(nik, nama) values("17339","PRIYO HADI SUSANTO");
insert into karyawan(nik, nama) values("17340","ARYO WICAKSONO");
insert into karyawan(nik, nama) values("17408","HANI IUDIARNO");
insert into karyawan(nik, nama) values("17502","PURWANITA ARY WIBAWATI");
insert into karyawan(nik, nama) values("18098","ACHMAD MIZANUL");
insert into karyawan(nik, nama) values("18195","MUS ADI FIRMANSYAH");
insert into karyawan(nik, nama) values("18364","INDRA SUSILO");
insert into karyawan(nik, nama) values("18472","M. MIFTAH FAHRUR R.");
insert into karyawan(nik, nama) values("18519","TRI SETIAWAN SUTANTO");
insert into karyawan(nik, nama) values("18828","HERU SETIAWAN");
insert into karyawan(nik, nama) values("18829","AGUS SULIANTO");
insert into karyawan(nik, nama) values("18979","HARIJO SUSENO");
insert into karyawan(nik, nama) values("19237","ANDIK SUWANDI");
insert into karyawan(nik, nama) values("19242","MUKHAMMAD SYAIFUDIN");
insert into karyawan(nik, nama) values("19243","BENY OKISTYAWAN");
insert into karyawan(nik, nama) values("19371","M. NURUN NADHIF");
insert into karyawan(nik, nama) values("19386","YUYUN WIBOWO");
insert into karyawan(nik, nama) values("19469","AGUS MULIYONO");
insert into karyawan(nik, nama) values("19512","MAHMUDIN");
insert into karyawan(nik, nama) values("19632","ADI TIYAS SETIAWAN");
insert into karyawan(nik, nama) values("19633","NANANG MISBAKHUL MUNIR");
insert into karyawan(nik, nama) values("19634","ANDRI PRIHANTONO");
insert into karyawan(nik, nama) values("19635","MUHAMAD MUNIR");
insert into karyawan(nik, nama) values("19636","ERWIN WICAKSONO");
insert into karyawan(nik, nama) values("19637","CATUR ENDRA OCTAVIANTO");
insert into karyawan(nik, nama) values("19638","MOCHAMAD ADE KURNIAWAN");
insert into karyawan(nik, nama) values("19641","M WAHYU SASAMANU");
insert into karyawan(nik, nama) values("19642","DANIEL EKA SAPUTRA");
insert into karyawan(nik, nama) values("19660","SAPTO KUNTJORO ABADI");
insert into karyawan(nik, nama) values("19661","KUSNANDAR");
insert into karyawan(nik, nama) values("19760","MUKHLASON");
insert into karyawan(nik, nama) values("19763","TULUS WAHYU UTOMO");
insert into karyawan(nik, nama) values("19766","FRANZKY RIZKY SANDY");
insert into karyawan(nik, nama) values("19820","WAHYU EKA PAZA");
insert into karyawan(nik, nama) values("19822","HOIRON KIKI ZAKARIAH");
insert into karyawan(nik, nama) values("19823","RIZAL WIDIANTORO");
insert into karyawan(nik, nama) values("19966","ENDRO SURYO");
insert into karyawan(nik, nama) values("19967","DOHIRIN");
insert into karyawan(nik, nama) values("19968","FAISAL LESTIOBUDI");
insert into karyawan(nik, nama) values("19969","EKO PURWANTO");
insert into karyawan(nik, nama) values("19970","MUHAMAD YATNO");
insert into karyawan(nik, nama) values("19994","EKO PUJI NOVIANTO");
insert into karyawan(nik, nama) values("19995","HARY PUJI WIYANTO");
insert into karyawan(nik, nama) values("19996","MUJI ASMANTO");
insert into karyawan(nik, nama) values("20023","YUDO KUSUMA");
insert into karyawan(nik, nama) values("20038","DWI ARIYANTO");
insert into karyawan(nik, nama) values("20040","TEGUH SARIONO");
insert into karyawan(nik, nama) values("20041","MURYANTO HADI PRANOTO");
insert into karyawan(nik, nama) values("20042","DENY UBAIDILLAH");
insert into karyawan(nik, nama) values("20043","AGUS DARMANTO");
insert into karyawan(nik, nama) values("20044","WARUJI");
insert into karyawan(nik, nama) values("20045","IMAM JAILANI");
insert into karyawan(nik, nama) values("20046","HENDRIEX APRIANTO");
insert into karyawan(nik, nama) values("20047","MIFTAHUL ULUM");
insert into karyawan(nik, nama) values("20048","SISWANTO");
insert into karyawan(nik, nama) values("20049","AMIRULZ FHANDJAYA");
insert into karyawan(nik, nama) values("20103","REFITA EDNA KAUTSAR");
insert into karyawan(nik, nama) values("20121","ABDUL BAQI");
insert into karyawan(nik, nama) values("20243","ABDILLAH");
insert into karyawan(nik, nama) values("20244","FENIK HARIANTO");
insert into karyawan(nik, nama) values("20246","MUCHAMAD ZAINUL ARIFIN");
insert into karyawan(nik, nama) values("20247","HERI KRISDIANTO");
insert into karyawan(nik, nama) values("20248","SYAIFUL ANWAR");
insert into karyawan(nik, nama) values("20249","MOCHAMMAD ANWAR");
insert into karyawan(nik, nama) values("20250","R. YANIS SETYO PRIBADI");
insert into karyawan(nik, nama) values("20257","MUHAMMAD AFANDI");
insert into karyawan(nik, nama) values("20259","MUCHAMMAD FATONI SUBKHAN");
insert into karyawan(nik, nama) values("20260","ABDUL HADI FAISOL ALKHADAD");
insert into karyawan(nik, nama) values("20261","ADI PRAJITNO");
insert into karyawan(nik, nama) values("20262","VERRY FATKHULLOH EKO. A");
insert into karyawan(nik, nama) values("20263","HANI JUNAEDI");
insert into karyawan(nik, nama) values("20264","SUPRI TEGUH SEBTYAN");
insert into karyawan(nik, nama) values("20391","HENDRA HARDANTO");
insert into karyawan(nik, nama) values("20467","SYAHADATAN AULIA SURYA");
insert into karyawan(nik, nama) values("20652","RAHMAT ALI YAHYA");
insert into karyawan(nik, nama) values("20751","MOCHAMAD SYARIFUDIN");
insert into karyawan(nik, nama) values("20797","SUNARIYO");
insert into karyawan(nik, nama) values("20798","MOHAMMAD SUHADAK");
insert into karyawan(nik, nama) values("20799","KHOIRUL ANAM");
insert into karyawan(nik, nama) values("20800","SOLEH KHODDIN");
insert into karyawan(nik, nama) values("20802","SUPRIADI");
insert into karyawan(nik, nama) values("20803","MOHAMAD BASORI");
insert into karyawan(nik, nama) values("20804","FERIANTO");
insert into karyawan(nik, nama) values("20926","DADANG SASMITA");
insert into karyawan(nik, nama) values("20928","DEDIK SETIAWAN");
insert into karyawan(nik, nama) values("20930","AGUS SUPRIANTO");
insert into karyawan(nik, nama) values("21267","RENDY PRAMANTA");
insert into karyawan(nik, nama) values("21458","DENY FRAHAJI");
insert into karyawan(nik, nama) values("21459","SAIFUL ANWAR");
insert into karyawan(nik, nama) values("21460","SANDI SATRIO UTOMO");
insert into karyawan(nik, nama) values("21461","MOCHAMMAD SHOFYAN");
insert into karyawan(nik, nama) values("21462","RATNO SOFYAN HARIYANTO");
insert into karyawan(nik, nama) values("21463","MOCHAMMAD FATMIR RIZA");
insert into karyawan(nik, nama) values("21464","MALIK MULYONO");
insert into karyawan(nik, nama) values("21465","M. HANAFI ZULKARNAEN");
insert into karyawan(nik, nama) values("21466","SONI HARIADI");
insert into karyawan(nik, nama) values("21467","MOCHAMAD ANTOK");
insert into karyawan(nik, nama) values("21468","BAKHTIAR BAYU NALURIO");
insert into karyawan(nik, nama) values("21469","HINDRIK WAHYU PRAMONO");
insert into karyawan(nik, nama) values("21705","AFIF FAELANI");
insert into karyawan(nik, nama) values("21706","BAGUS PRAYITNO");
insert into karyawan(nik, nama) values("21711","KHUSAINI");
insert into karyawan(nik, nama) values("21712","MUHAMMAD ASFA'UDIN");
insert into karyawan(nik, nama) values("21713","SUGENG HARIONO");
insert into karyawan(nik, nama) values("23847","BUDI UTOMO");
insert into karyawan(nik, nama) values("24327","ADITYA LUKMANSYAH");
insert into karyawan(nik, nama) values("23247","ELISA GINTING");
insert into karyawan(nik, nama) values("24801","KHOIRUL HAMDANI ");
insert into karyawan(nik, nama) values("08171","RISKY ADI WIBOWO");
insert into karyawan(nik, nama) values("15458","ANDRIE JUNAIDI");
insert into karyawan(nik, nama) values("10799","M. SHOLEHFUDDIN HIDAYAT");
